spring:
  datasource:
#    url: jdbc:h2:tcp://localhost/~/jpashop      # ??? H2 DB? url
    username: sa
#    password:      # ??? ??? ??
    driver-class-name: org.h2.Driver      # ??? DB ????

  jpa:
    hibernate:
      ddl-auto: create      # ???? ?? ????? ?
    properties:
      hibernate:
        format_sql: false      # ???? sql? ??? ???
        show_sql: false     # System.out? ??? sql? ??
#        dialect: org.hibernate.dialect.H2Dialect

logging:
  level:
    org.hibernate.sql: debug      # Logger? ??? sql? ??
